---
#sample configuration file, should be located at /etc/fancontrol.yaml

# /sys/class/hwmon node declarations, uses the 'name' file content (/sys/class/hwmonX/name)
# to determine proper hwmon path for binding as hwmonX are not persistent
hwmon:
# - it8665
# - k10temp
# - amdgpu

# Sensor binding
# Sensor types:
# 1. hwmon node. Contain attributes:
#   type - points to the hwmon entry declared in the above section
#   bind - points to the file name which should be read, e.g. 'temp1' will represent
#     /sys/class/hwmonX/temp1_input
# 2. shell_cmd, uses shell command to retrieve sensor data, the command output format should be
# an integer value of temperature in degree units.
sensors:
#  - cpu: { type: it8665, bind: temp1 }
#  - mb: { type: it8665, bind: temp2 }
#  - wd12: { type: shell_cmd, bind: "hddtemp /dev/sdd | tail -c 6 | head -c -4" }
#  - wd8: { type: shell_cmd, bind: "hddtemp /dev/sdc | tail -c 6 | head -c -4" }

# PWM channel binding
# type: hwmon node entry, defined in 'hwmon' section
# bind: points to the file name which will be used for control, e.g. 'pwm1' will represent
#   /sys/class/hwmonX/pwm1
# mode: 'dc' - DC channel mode, 'pwm' - PWM channel mode, default - no change
# minpwm, maxpwm: allowed PWM range, corresponds to the range of used fan,
#   could be found experimentally
# fan_stop: boolean option, if true, the fan will be completely stopped
#   if the temperature getting smaller than the lowest value defined.
#   If set to true, implicitly defines fan_stop_hysteresis = 3.
#   Default value: false
# fan_stop_hysteresis: fan start/stop hysteresis value in degrees Celsius,
#   e.g. if controller defines lowest temperature setting as 50 and hysteresis equals to 5,
#   the fan will be stopped after reaching 45 degrees and then will be started at 50 degrees.
#   This item also implicitly defines fan_stop = true.
#   Default value: 3
pwms:
#  - cpu_main: { type: it8665, bind: pwm1, mode: dc, minpwm: 110, maxpwm: 255 }
#  - cpu_aux: { type: it8665, bind: pwm6, mode: pwm, minpwm: 30, maxpwm: 230 }
#  - cha: { type: it8665, bind: pwm2, mode: dc, minpwm: 90, maxpwm: 255, fan_stop: true }

# Controller binding
# Links sensor declarations to pwm declarations with defined control algorithm
# Can link multiple sensors to the multiple pwms.
# sensor: Sensor binding entry. Can be multiple, highest temperature will be used as a reference
# pwm: PWM channel binding entry. Can be multiple, each pwm will be controlled according to the
#   allowed PWM range
# mode: control algorithm, possible values:
# 1. two_point - simple 2 point curve transformation
# 2. multi_point - arbitrary amount of approximation points
# 3. pi - proportional-integral control algorithm
#
# poll: polling options, can contain:
# 1. time - sampling time in seconds('s' suffix or absent)
#    or milliseconds('ms' suffix), default value = 1s
# 2. ma_samples - amount of samples for moving average sensor reading mode, disabled if not exist
#
# set: special options for selected control algorithm (mode)
# 1. For 'two_point' it contains min and max allowed temperature: 'a', 'b'
# - min temperature maps to the 'minpwm' value
# - max temperature maps to the 'maxpwm' value
#
# 2. For "multi_point' it contains the points array (arbitrary amount of points),
# each point contain temperature and pwm value mapping,
# pwm value is defined in percents between minpwm and maxpwm value, e.g
# if minwm=100, maxpwm=200 the point {50: 30} will declare that at 50C
# the raw pwm value should be 130
#
# 3. For 'pi' it contains:
# t - desired temperature setting
# kp - proportional coefficient
# ki - integral coefficient
# max_i - maximum allowed value for I component in percents, default value = 50
controllers:
#  - cpu: { sensor: cpu, pwm: { cpu_main, cpu_aux, cha }, mode: two_point,
#      poll: { time: 1s, ma_samples: 8 }, set: { a: 50, b: 78 }
#    }
#  - cha1: { sensor: { wd8, wd12 }, pwm: cha, mode: pi, poll: { time: 2s, ma_samples: 8 },
#      set: { t: 50, kp: 2, ki: 0.1, max_i: 60 }
#    }
#  - cha2: { sensor: wd4, pwm: cha, mode: multi_point, poll: 30s,
#    set: {{ 40 : 0 }, { 50 : 50 }, { 60 : 100 }}
#    }
#  - aux: { sensor: cpu, pwm: cha , mode: two_point, poll: 5s,
#     set: { a: 40, b: 75 }
#    }
#  - cpu_multi: { sensor: cpu, pwm: { cpu_main, cpu_aux, cha }, mode: multi_point,
#     poll: { time: 1s, ma_samples: 8 },
#     set: {{ 40 : 0 }, { 55 : 20 }, { 78 : 100 }}
#    }
