---

hwmon:
 - it8665
 - k10temp
 - amdgpu

sensor:
  - cpu: { type: it8665, bind: temp1 }
  - mb: { type: it8665, bind: temp2 }
  - wd12: { type: shell_cmd, bind: "hddtemp /dev/sdd | tail -c 6 | head -c -4" }
  - wd8: { type: shell_cmd, bind: "hddtemp /dev/sdc | tail -c 6 | head -c -4" }

pwm:
  - cpu: { type: it8665, mode: dc, bind: pwm1, minpwm: 70, maxpwm: 255 }
  - cha: { type: it8665, mode: pwm, bind: pwm2, minpwm: 70, maxpwm: 255 }

controller:
  - cpu: { sensor: cpu, pwm: { cpu, cha }, mode: 2point, poll: { time: 5s, ma_samples: 4 },
      set: { temp_a: 40, temp_b: 75 }
    }
  - cha: { sensor: { wd8, wd12 }, pwm: cha, mode: pi, poll: 30s,
      set: { temp: 42, p: 10, i: 5 }
    }

daemon_conf:
  - mqtt_telemetry: { enable: true, broker: localhost, port: 1883, prefix: serv_fanctrl }
